### ISSUE TITLE
SPORE Show Cases

### ISSUE THREAD

**Issue by kappeld** [IGITUGraz/spore-nest-module#1]
This thread is not an actual issue but a collection of show cases SPORE was used for so far. Follow up to this thread to add a demo of your own project. I make a start with our little pattern matching experiment, which you also find [here](https://github.com/IGITUGraz/spore-nest-module/tree/master/examples/pattern_matching_showcase):

![spore-pattern-result-1](https://cloud.githubusercontent.com/assets/22887425/24467479/f7235d1c-14b4-11e7-8ecf-ba19931d7f8d.gif)

Another version with higher resolution and longer recording:

![spore-pattern-result-2](https://cloud.githubusercontent.com/assets/22887425/24467512/1aa0caa4-14b5-11e7-9217-29dcf48ac349.gif)

**Comment by anandtrex** [comment]
Cool!!!

**Comment by mhoff** [comment]
We might consider moving the showcase to the wiki-pages.

**Comment by kappeld** [comment]
We could also just close this issue, since the pattern matching showcase is already described in:

https://github.com/IGITUGraz/spore-nest-module/tree/master/examples/pattern_matching_showcase

I just found it initially interesting to have a place where everyone can easily post demos. But probably this is not the best solution anyway, and hardly anyone will ever use it.
