### ISSUE TITLE
Release Version 2.12.0

### ISSUE THREAD

**Issue by kappeld** [IGITUGraz/spore-nest-module#10]
After issue #8 is closed and #710 of NEST has been merged into their master, it would be a good time to create an official release version of SPORE. This thread is here as a reminder and for collecting minor changes that should be made before creating the release version.

**Comment by kappeld** [comment]
**TODOs:**

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/poisson_dbl_exp_neuron.cpp#L434

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/reward_in_proxy.cpp#L136


**cout(s):**

The only occurrence of `std::cout` seems to be here:

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/reward_in_proxy.cpp#L217

@mhoff should we replace this with something nicer, e.g. LOG?


**Unused includes:**

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/reward_in_proxy.cpp#L50 (?)

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/test_circular_buffer.cpp#L29

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/test_tracing_node.cpp#L29

* https://github.com/IGITUGraz/spore-nest-module/blob/master/src/test_pulse_trace.cpp#L29

**Comment by kappeld** [comment]
I was thinking about one more general problem with the current design of SPORE:

Neuron types that can be used together with our synapse models need to be derived from TracingNode, to get access to the BAP trace that is used as a learning signal. In the current implementation the inheritance structure looks like this:

nest::Node <-- spore::TracingNode <-- MyNewNeuronModel

see: https://github.com/IGITUGraz/spore-nest-module/blob/master/src/tracing_node.h

Now that I thought about it again, this seems a bit problematic, since If one wants to write a neuron model that is also compatible with standard STDP synapses in NEST, the neuron model needs to be derived from ArchivingNode. So one will want to multi-inheritance and do something like this:

nest::ArchivingNode, spore::TracingNode <-- MyNewNeuronModel

which now is an ugly "diamond-structured" inheritance since nest::ArchivingNode is already derived from nest::Node. My feeling is that we will quite soon want to do something like this, i.e. mix different models form NEST and SPORE, so we should keep this opportunity open and as straightforward as possible.

Since TracingNode does not use any features of nest::Node, but really just provides the interface to get and set traces, I don't see a good reason to actually derive it from nest::Node now. If we just dropped that inheritance everything would become much simpler it seems to me. Also it would be easy to derive neuron models form built-in nest neurons like this:

nest::SomeBuiltinNestNeuronModel, spore::TracingNode <-- MyNewNeuronModel

@mhoff I think we had this discussion already, but I can't remember why we ended up preferring the current solution, do you?

@anandtrex What are your emotions about multi-inheritance? Do you see any problem with this?

@mhoff What was the reason to make get_trace_status() virtual? I don't see a benefit in doing this. I would like to keep the TracingNode as slim as possible. Can I remove the virtual classifier here?

**Comment by mhoff** [comment]
> @mhoff I think we had this discussion already, but I can't remember why we ended up preferring the current solution, do you?

I think we had essentially two arguments: 1) It works. 2) You can easily drop a `TracingNode` everywhere a `Node` can go.

> @mhoff What was the reason to make get_trace_status() virtual? I don't see a benefit in doing this. I would like to keep the TracingNode as slim as possible. Can I remove the virtual classifier here?

No reason. Can be removed.

**Comment by anandtrex** [comment]
@kappeld I agree that if TracingNode doesn't use any nest features, it's better for it to not inherit from nest::Node. In that case, the multiple inheritance would be relatively clean (it's more like a mixin).

**Comment by kappeld** [comment]
Ok. I will apply these changes then. Since literally every model in NEST is derived from ArchivingNode except the reward in proxy, and we want to use both in SPORE, this seems to me the cleanest solution.

**Comment by kappeld** [comment]
I tried this out now. The main downside of this solution is that we now have to `dynamic_cast` the post-synaptic neuron on each input spike. This actually gives us measurable performance cost of 1-2% (I did not think that `dynamic_cast` is actually *that* costly...). What do you think? Is this worth the slightly more general solution? Otherwise I could just go back to the old solution and keep this in mind until the problem actually does occur...

**Comment by mhoff** [comment]
Oh wow. I mean I thought about this when I tried to remember our discussion, but I did not expect a significant performance drop through casting.

Honestly, in my opinion `dynamic_cast` is a not very nice solution for this situation, even without the performance drop. I would prefer the virtual inheritance diamond instead..

What about including the NEST guys in this discussion? I think our use case is not *that* special and maybe they come up with a nice idea or some long term change in NEST which would allow for an even cleaner solution.

**Comment by kappeld** [comment]
Me neither, I was quite surprised to see a noticeable effect. I don't think virtual inheritance avoids the `dynamic_cast` though, it probably makes things worse. I still find multi-inheritance would be a quite clean solution...

I think the proper way to go is to use the feature of the NEST connection that allows to specify the targetidentifierT (each connection is a template that takes this as template argument). Probably one needs to write the base class of the connection for SPORE from scratch, with special features tailored towards our requirements, to do it really nicely. However, I never dug into this, so it probably requires a bit more work...

Anyway this is a luxury problem. I will stash these changes and think about it a bit more... This does not really effect any user of SPORE so we can apply these changes whenever we come up with a good solution.

**Comment by kappeld** [comment]
Ok. This pretty much completes our TODO list for the release version.

Are there any other urgent points?

Is anybody sill motivated to do the formatting of the python code?

**Comment by mhoff** [comment]
> Is anybody sill motivated to do the formatting of the python code?

Done.
