### ISSUE TITLE
Make logos more portable

### ISSUE THREAD

**Issue by mhoff** [IGITUGraz/spore-nest-module#13]
Our custom NEST logos use a specific font (Courier New) which is not necessarily installed on every system. We should convert those strings to plain SVG shapes to provide better portability.

**Comment by kappeld** [comment]
I agree. I actually wanted to do that already, because I saw that there is sometimes a problem with the fonts, but then forgot about it. E.g. Inkscape provides a function to translate objects to paths, also works for text and should do the trick.

**Comment by mhoff** [comment]
Should be fixed by 2e8daed4c3b3eaec8c62660dd70518a096300c2c (?). There are still traces of 'Courier New' in the SVG source. However, they seem to have no effect. It could be that inkscape simply does not properly clean up the style specification after conversion. Can someone double-check?

**Comment by kappeld** [comment]
Looks good to me. Thanks!
