### ISSUE TITLE
Make SPORE citable

### ISSUE THREAD

**Issue by mhoff** [IGITUGraz/spore-nest-module#14]
As of [this tutorial](https://guides.github.com/activities/citable-code/), GitHub repositories can be turned into DOI references using zenodo.

For this, I think the repository owner (IGITUGraz) has to allow zenodo to access its data.

@anandtrex Could you give that a look? If so, I would also like to assist you in this.

**Comment by anandtrex** [comment]
I have given Zenodo access to this repository. Now if you create a new release on github it should automatically assign a DOI according to their documentation.

**Comment by mhoff** [comment]
Good. Seems like we all can access the zenodo interface with our individual accounts as we are members of the organization.

Do we have to recreate 2.12.0 now? Can we even recreate a release (for the same commit) without breaking something (like rendering the old URL invalid)?

**Comment by kappeld** [comment]
No. Please don't create a new release for the same commit. This really would not make sense and is just confusing. If there is no alternative solution, we can just make a 2.12.1 with some bug fixes later next week or so (I already found some small bugs but I have to test my fixes before I commit).

**Comment by mhoff** [comment]
I was only considering deleting & creating again the exact release we had before to trigger the web-hook. As a release is essentially context information for an existing tag, this might be possible without any interference. However, I did not find any statements proving this hypothesis. Hence, I would agree to play safe and wait for 2.12.1.

**Comment by kappeld** [comment]
A NEST 2.12.1 release seems to be on its way according to: https://github.com/nest/nest-simulator/pull/739#pullrequestreview-42235591

I guess we best wait until this release is out and then issue our corresponding 2.12.1 to stay in synch with the version number of NEST.

**Comment by mhoff** [comment]
Just for future reference: NEST decided to skip 2.12.1 and to create a proper 2.14.0 release before NEST 3.0.

I just checked the [Zenodo page](https://zenodo.org/account/settings/github/repository/IGITUGraz/spore-nest-module) and it seems like we are indeed all set up to create a release (at least in terms of *this* issue).

Closing the issue.
