### ISSUE TITLE
Create a requirements.txt for python dependencies

### ISSUE THREAD

**Issue by anandtrex** [IGITUGraz/spore-nest-module#19]

**Comment by kappeld** [comment]
Would be nice. We can just extract the information from the installation guide. required packages are:

```
cython
mpi4py
pyzmq
numpy
ujson
matplotlib
```
anything I forgot?

**Comment by anandtrex** [comment]
Looks good.

**Comment by kappeld** [comment]
I tested it now for new user homes for the students. The requirements.txt works. I also included minimum version numbers. I guess this concludes this issue.

**Comment by mhoff** [comment]
Approved.
