### ISSUE TITLE
set_status does not handle gradient_scale anymore

### ISSUE THREAD

**Issue by mhoff** [IGITUGraz/spore-nest-module#3]
With e8d7c6c309e718218ba59c1c46244c9402a4e275, using `set_status` on the synapse can not set the parameter `gradient_scale` anymore. The showcase fails because of this.

**Comment by mhoff** [comment]
@kappeld maybe it does make sense to run the pattern_matching experiment (without the interface) for a few seconds as one of the tests. This could be seen as a form of integration test, as it includes most of the relevant components.

**Comment by kappeld** [comment]
Yes, agreed. I'll fix the problem when setting the parameter.

**Comment by mhoff** [comment]
Fixed by a3976ede1c1544bfe2e9ee43841efd737c2b6df8.
